### ISSUE TITLE
getting value error while running estimate_irt_params.sh script to generate response

### ISSUE THREAD

**Issue by charchit7** [nyu-mll/nlu-test-sets#5]
elbo loss:   0%|                                                                                                              | 0/500 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "/home/username/nlu-test-sets/irt_scripts/variational_irt.py", line 604, in <module>
    main(args)
  File "/home/username/nlu-test-sets/irt_scripts/variational_irt.py", line 474, in main
    _ = train(
  File "/home/username/nlu-test-sets/irt_scripts/variational_irt.py", line 318, in train
    elbo_loss = svi_kernel.step(weights, data_)
  File "/home/username/nlu-test-sets/irt_scripts/weighted_ELBO.py", line 173, in step
    loss = self.loss_and_grads(self.model, self.guide, weights, *args, **kwargs)
  File "/home/username/nlu-test-sets/irt_scripts/weighted_ELBO.py", line 115, in loss_and_grads
    for model_trace, guide_trace in self._get_traces(model, guide, args, kwargs):
  File "/home/username/miniconda3/envs/mark1/lib/python3.9/site-packages/pyro/infer/elbo.py", line 182, in _get_traces
    yield self._get_trace(model, guide, args, kwargs)
  File "/home/username/nlu-test-sets/irt_scripts/weighted_ELBO.py", line 30, in _get_trace
    model_trace, guide_trace = get_importance_trace(
  File "/home/username/miniconda3/envs/mark1/lib/python3.9/site-packages/pyro/infer/enum.py", line 80, in get_importance_trace
    check_site_shape(site, max_plate_nesting)
  File "/home/username/miniconda3/envs/mark1/lib/python3.9/site-packages/pyro/util.py", line 437, in check_site_shape
    raise ValueError(
ValueError: at site "b", invalid log_prob shape
  Expected [], actual [82756]
  Try one of the following fixes:
  - enclose the batched tensor in a with pyro.plate(...): context
  - .to_event(...) the distribution being sampled
  - .permute() data dimensions

Can anyone please help me with this, this would help me a lot. Thanks :)

**Comment by charchit7** [comment]
@zphang @claravania @phu-pmh please help.

**Comment by charchit7** [comment]
first few lines shows this as well : 

Alpha Std 0.3, Diff Guess Std 1.0
Missing:
 **set()** 
Use all examples:
abductive-nli num test items:  766

Is set something I am missing?

**Comment by charchit7** [comment]
It's pyro library issues it seems.
